import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Top 3 Websites of 2024 | Easy Coding Tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className='Footer'>
          <p>All Right Reserved | <Link href={'https://www.youtube.com/channel/UCHahklg_h-WQhiYRUT_P0hw'} target="_blank">&copy; Easy Coding Tutorial</Link></p>
        </div>
      </body>
    </html>
  );
}
